services:
  dashboard:
    build: .
    container_name: flight-price-dashboard
    environment:
      TZ: "Europe/Vienna"
    command: uv run app/dash_app.py
    ports:
      - "8000:8000"
    volumes:
      - ./flight_database.db:/app/flight_database.db:Z
    restart: always

  tracker:
    build: .
    container_name: flight-price-tracker
    environment:
      TZ: "Europe/Vienna"
    command: uv run main.py
    volumes:
      - ./flight_database.db:/app/flight_database.db:Z
      - ./searches.json:/app/searches.json:Z
      - ./google_credentials.json:/app/google_credentials.json:Z
      - ./logs/tracker.log:/app/logs/tracker.log:Z
      - ./logs/scraper.log:/app/logs/scraper.log:Z
      - ./logs/search_manager.log:/app/logs/search_manager.log:Z
    env_file:
      - .env
    init: true
    shm_size: 2gb